version: "3.9"
services:
  app:
    image: thbst16/dotnet-signalr-rosetta-stone:latest
    ports:
      - "80:80"
    volumes:
      - azure-mount:/app/config
    extra_hosts:
      - "host.docker.internal:host-gateway"